alias git="LANG=en_US git"
alias gb='git branch'
alias gl='git log'
alias gap='git add -p'
alias ga='git add'
alias gg='git log --all --graph --abbrev-commit --decorate --date=relative --format=format:"%C(bold blue)%h%C(reset) - %C(bold yellow)%d%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset) - %C(bold green)(%ar)%C(reset)"'
alias glo='git log --oneline'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcam='git commit --amend'
alias gd='git diff'
alias gpull='git pull'
alias gpush='git push'
alias gs='git status'
alias gco='git checkout'
alias ll='ls -alh'
alias gsub='git submodule update --init --recursive'
